name: build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull down my website
        run: |
          git clone https://github.com/haoyang9804/haoyang9804.github.io.git website
          cd website
          pwd
      - name: update docs/CompilerCorrectness.md
        run:
          cp README.md website/docs/CompilerCorrectness.md
      - name: update my website
        run:
          cd website
          pwd
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "update CompilerCorrectness.md"
          git push https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/haoyang9804/haoyang9804.github.io
